apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: economy-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: ssh://git@git.local/jonas/economy-platform.git
    targetRevision: main
    path: infra/k8s/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: economy
